In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('creditcard.csv')
data

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [4]:
np.unique(data['Class'], return_counts=True)

(array([0, 1], dtype=int64), array([284315,    492], dtype=int64))

In [5]:
492/(len(data))

0.001727485630620034

In [6]:
from sklearn.neighbors import LocalOutlierFactor

In [7]:
lof=LocalOutlierFactor(n_neighbors=20 , contamination=0.002)

In [9]:
x=data.drop('Class' , axis=1)

In [10]:
y_pred=lof.fit_predict(x)

In [11]:
np.unique(y_pred,return_counts=True)

(array([-1,  1]), array([   570, 284237], dtype=int64))

In [12]:
y_pred[y_pred==1]=0
y_pred[y_pred==-1]=1

In [13]:
y_true=data['Class']

In [14]:
from sklearn import metrics

In [15]:
print(metrics.classification_report(y_true , y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    284315
           1       0.05      0.05      0.05       492

    accuracy                           1.00    284807
   macro avg       0.52      0.53      0.52    284807
weighted avg       1.00      1.00      1.00    284807



In [16]:
from pyod.models import abod

In [17]:
abod_od=abod.ABOD(n_neighbors=20 , contamination=0.002)

In [18]:
y_pred=abod_od.fit_predict(x)

C:\Program Files\anakonda\Lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function fit_predict is deprecated
  warnings.warn(msg, category=FutureWarning)


In [19]:
np.unique(y_pred , return_counts=True)

(array([0, 1]), array([284237,    570], dtype=int64))

In [20]:
print(metrics.classification_report(y_true , y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    284315
           1       0.00      0.00      0.00       492

    accuracy                           1.00    284807
   macro avg       0.50      0.50      0.50    284807
weighted avg       1.00      1.00      1.00    284807



In [21]:
from sklearn.ensemble import IsolationForest

In [22]:
IF=IsolationForest(contamination=0.005)

In [23]:
y_pred=IF.fit_predict(x)

In [24]:
np.unique(y_pred,return_counts=True)

(array([-1,  1]), array([  1425, 283382], dtype=int64))

In [25]:
y_pred[y_pred==1]=0
y_pred[y_pred==-1]=1

In [27]:
print(metrics.classification_report(y_true,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    284315
           1       0.12      0.33      0.17       492

    accuracy                           0.99    284807
   macro avg       0.56      0.66      0.58    284807
weighted avg       1.00      0.99      1.00    284807



In [30]:
print(metrics.confusion_matrix(y_true,y_pred))

[[283054   1261]
 [   328    164]]


In [31]:
df=pd.read_csv('shuttle.csv' , header=None, names=['LastLoginDays', 'NumberOfLoginLastWeek', 'NumberOfLikesLastWeek',
                                                   'IIE', 'NLS', 'LKK', 'LAI', 'LAK', 'ODK', 'OKO'])

In [32]:
df.head()

LastLoginDays  NumberOfLoginLastWeek  NumberOfLikesLastWeek  IIE  NLS  LKK  \
0             50                     21                     77    0   28    0   
1             53                      0                     82    0   52   -5   
2             37                      0                     76    0   28   18   
3             37                      0                     79    0   34  -26   
4             85                      0                     88   -4    6    1   

   LAI  LAK  ODK  OKO  
0   27   48   22    1  
1   29   30    2    0  
2   40   48    8    0  
3   43   46    2    0  
4    3   83   80    1

In [34]:
IF=IsolationForest(contamination=0.01)

In [38]:
y_pred=IF.fit_predict(df.values)

In [39]:
np.unique(y_pred,return_counts=True)

(array([-1,  1]), array([  491, 48606], dtype=int64))

In [40]:
df['Anomaly']=y_pred